### ISSUE TITLE
error compiling project

### ISSUE THREAD

**Issue by yayitswei** [cipherzzz/erc20-megawallet#1]
Hi, thanks for the helpful example and associated article. I installed all the tools as outlined in your article. When I try to run `truffle compile`, I'm told that the version of solidity (0.5.0) doesn't match the required version (0.4.2). After installing the correct solidity version with `npm install npm install solc@0.4.2`, when I run `truffle compile` again I get the following error message:

```
$ truffle compile
SyntaxError: Error parsing /Users/wei/code/hexbite/kinakuta/erc20-megawallet/contracts/ERC20Wallet.sol: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.parseImports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/parser.js:54:1)
    at Object.getImports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:374:1)
    at Promise.all.then.results (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:346:1)
Truffle v5.0.0 (core: 5.0.0)
Node v11.1.0
```

Any troubleshooting suggestions? Thanks!

**Comment by yayitswei** [comment]
Looks like this compiles successfully if I downgrade my truffle version.

```
$ npm i -g truffle@^4.0.0
...
$ truffle v
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
```
